version: "3.9"
services:
 ticket_nginx:
   container_name: ticket_nginx
   image: nginx:1.17.8
   ports:
     - 9001:80
   volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
     - ../:/var/www
   links:
     - ticket_php
   network_mode: "bridge"
 ticket_php:
   container_name: ticket_php
   build: ./php
   working_dir: /var/www
   volumes:
     - ../:/var/www
   network_mode: "bridge"
